par(mar=c(3,4,3,1),cex=1.5,xpd=TRUE,mfrow=c(1,2))
wm_trend<-barplot(d_freq_monthly$frequency,names.arg = c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),las=2,ylim=c(0,0.7),ylab="Frequency of consumption",col="indianred",border=NA)
lines(x=wm_trend,y=d_freq_monthly_pfnl[,2],col="olivedrab3",lwd=4)
points(x=wm_trend,y=d_freq_monthly_pfnl[,2],col="olivedrab3",pch=18)
lines(x=wm_trend,y=d_freq_monthly_fish[,2],col="steelblue1",lwd=3)
points(x=wm_trend,y=d_freq_monthly_fish[,2],col="steelblue1",pch=18)
mtext("a)",cex=1.5,side=3,line=1,adj=-0.3) 
q_wm_trend<-barplot(d_quant_monthly$grams_AME,col="indianred4",border=NA,
                    names.arg = c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),las=2,ylim=c(0,140),ylab="gr/AME/day")
lines(x=q_wm_trend,y=d_quant_monthly_fish$grams_AME,col="steelblue3",lwd=4)
points(x=q_wm_trend,y=d_quant_monthly_fish$grams_AME,col="steelblue3",pch=18)
lines(x=q_wm_trend,y=d_quant_monthly_insect$grams_AME,col="olivedrab",lwd=4)
points(x=q_wm_trend,y=d_quant_monthly_insect$grams_AME,col="olivedrab",pch=18)
mtext("b)",cex=1.5,side=3,line=1,adj=-0.35) 
